version: "3"

services:
  # Server
  server:
    container_name: server
    build: .
    env_file: .env
    restart: always
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    depends_on:
      - database
    links:
      - database

  # MariaDB
  database:
    container_name: database
    image: mariadb:bionic
    env_file: .env
    restart: always
    ports:
     - 3306:3306